### ISSUE TITLE
math.type: Required value: math transform type is required - type Multiplay is missing

### ISSUE THREAD

**Issue by haarchri** [crossplane-contrib/crossplane-migrator#21]
pld p&t:
```
          transforms:
          - math:
              multiply: 1024
            type: math
```

`crossplane-migrator new-pipeline-composition -i database/sqlinstance/composition-mariadb.yaml -o xx.yaml`

after migration:
```
          transforms:
          - math:
              multiply: 1024
            type: math
```

error: 
`crossplane: error: cannot render composite resource: pipeline step "patch-and-transform" returned a fatal result: invalid Function input: resources[0].patches[3].transforms[0].math.type: Required value: math transform type is required`

```
                transforms:
                - math:
                    multiply: 1024
                    type: Multiply
                  type: math
```
